include $(TOPDIR)/rules.mk
LUCI_TITLE:=fros system
LUCI_PKGARCH:=all
LUCI_DEPENDS:=
PKG_NAME:=luci-app-fros
PKG_VERSION:=1.0
PKG_RELEASE:=1
include $(TOPDIR)/feeds/luci/luci.mk
# call BuildPackage - OpenWrt buildroot signature
